package com.sms.paymentgateway.utils.security

import android.content.Context
import android.content.SharedPreferences
import dagger.hilt.android.qualifiers.ApplicationContext
import timber.log.Timber
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class SecurityManager @Inject constructor(
    @ApplicationContext private val context: Context
) {

    private val prefs: SharedPreferences =
        context.getSharedPreferences("security_prefs", Context.MODE_PRIVATE)

    // ─── API Key ────────────────────────────────────────────────────────────
    fun getApiKey(): String =
        prefs.getString("api_key", null) ?: generateAndSaveApiKey()

    fun validateApiKey(providedKey: String?): Boolean {
        if (providedKey.isNullOrBlank()) return false
        return providedKey == getApiKey()
    }

    fun regenerateApiKey(): String {
        val newKey = generateRandomString(32)
        prefs.edit().putString("api_key", newKey).apply()
        Timber.i("تم تجديد مفتاح API")
        return newKey
    }

    private fun generateAndSaveApiKey(): String {
        val key = generateRandomString(32)
        prefs.edit().putString("api_key", key).apply()
        Timber.i("تم إنشاء مفتاح API جديد")
        return key
    }

    // ─── HMAC ───────────────────────────────────────────────────────────────
    fun generateHmacSignature(data: String): String {
        return try {
            val secret = prefs.getString("hmac_secret", null) ?: generateAndSaveHmacSecret()
            val mac = Mac.getInstance("HmacSHA256")
            mac.init(SecretKeySpec(secret.toByteArray(), "HmacSHA256"))
            mac.doFinal(data.toByteArray()).joinToString("") { "%02x".format(it) }
        } catch (e: Exception) {
            Timber.e(e, "خطأ في إنشاء توقيع HMAC")
            ""
        }
    }

    fun verifyHmacSignature(data: String, signature: String): Boolean =
        generateHmacSignature(data).equals(signature, ignoreCase = true)

    private fun generateAndSaveHmacSecret(): String {
        val secret = generateRandomString(64)
        prefs.edit().putString("hmac_secret", secret).apply()
        return secret
    }

    // ─── IP Whitelist ───────────────────────────────────────────────────────
    fun isIpAllowed(ip: String): Boolean {
        val whitelist = getIpWhitelist()
        if (whitelist.isEmpty()) return true
        return whitelist.contains(ip) || whitelist.contains("*")
    }

    fun getIpWhitelist(): Set<String> =
        prefs.getStringSet("ip_whitelist", emptySet()) ?: emptySet()

    fun addIpToWhitelist(ip: String) {
        val list = getIpWhitelist().toMutableSet().also { it.add(ip) }
        prefs.edit().putStringSet("ip_whitelist", list).apply()
    }

    fun removeIpFromWhitelist(ip: String) {
        val list = getIpWhitelist().toMutableSet().also { it.remove(ip) }
        prefs.edit().putStringSet("ip_whitelist", list).apply()
    }

    fun clearIpWhitelist() {
        prefs.edit().remove("ip_whitelist").apply()
    }

    // ─── Webhook ────────────────────────────────────────────────────────────
    fun getWebhookUrl(): String? = prefs.getString("webhook_url", null)
    fun setWebhookUrl(url: String) {
        prefs.edit().putString("webhook_url", url).apply()
    }

    fun getWebhookSecret(): String? = prefs.getString("webhook_secret", null)
    fun setWebhookSecret(secret: String) {
        prefs.edit().putString("webhook_secret", secret).apply()
    }

    // ─── Relay Server URL ───────────────────────────────────────────────────
    fun getRelayUrl(): String? = prefs.getString("relay_url", null)
    fun setRelayUrl(url: String) {
        prefs.edit().putString("relay_url", url).apply()
        Timber.i("تم تحديث رابط Relay: $url")
    }

    fun clearRelayUrl() {
        prefs.edit().remove("relay_url").apply()
    }

    // ─── Direct Connection URL (generated by device) ────────────────────────
    /**
     * ينشئ رابط الاتصال المباشر للجهاز بناءً على رابط Relay + API Key
     * مثال: https://relay.example.com/api/v1  (مع API Key جاهز للاستخدام)
     */
    fun buildDirectApiUrl(): String? {
        val relay = getRelayUrl() ?: return null
        // تحويل wss:// إلى https:// وإزالة /device
        val baseUrl = relay
            .replace("wss://", "https://")
            .replace("ws://", "http://")
            .removeSuffix("/device")
        return "$baseUrl/api/v1"
    }

    /**
     * ينشئ رمز QR / بطاقة الاتصال الكاملة
     */
    fun buildConnectionCard(): ConnectionCard? {
        val apiUrl = buildDirectApiUrl() ?: return null
        val apiKey  = getApiKey()
        return ConnectionCard(
            apiUrl     = apiUrl,
            apiKey     = apiKey,
            curlExample = "curl -X POST $apiUrl/transactions \\\n" +
                    "  -H \"Authorization: Bearer $apiKey\" \\\n" +
                    "  -H \"Content-Type: application/json\" \\\n" +
                    "  -d '{\"id\":\"order-1\",\"amount\":500,\"phoneNumber\":\"01012345678\"}'",
            jsExample  = buildJsExample(apiUrl, apiKey)
        )
    }

    private fun buildJsExample(url: String, key: String) = """
const API_URL = "$url";
const API_KEY = "$key";

async function createPayment(orderId, amount, phone) {
  const res = await fetch(`${'$'}{API_URL}/transactions`, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${'$'}{API_KEY}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({ id: orderId, amount, phoneNumber: phone })
  });
  return res.json();
}""".trimIndent()

    // ─── Helpers ────────────────────────────────────────────────────────────
    private fun generateRandomString(length: Int): String {
        val chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
        return (1..length).map { chars.random() }.joinToString("")
    }
}

data class ConnectionCard(
    val apiUrl: String,
    val apiKey: String,
    val curlExample: String,
    val jsExample: String
)
